#!/bin/sh

if [ ! -f /dev/shm/bw-session ]; then
  BW_SESSION=$(bw unlock --raw)
  if [ -z "$BW_SESSION" ]; then
    echo "Could not unlock BW vault" >&2
    exit 1
  fi
  echo "export BW_SESSION=\"$BW_SESSION\"" > /dev/shm/bw-session
fi

. /dev/shm/bw-session

bw "$@"
